name: lucid-from-html
version: '0.7.0'
synopsis: Tool to convert HTML to Lucid code.
description: ! 'Tool that converts HTML files to Haskell code, ready to be

  used with the Lucid library.'
category: Text
author: Oleg Tsybulskyi, David Baynard, Jasper Van der Jeugt, Simon Meier
maintainer: alogic0@gmail.com
license: BSD3
github: alogic0/lucid-from-html
dependencies:
- base
- containers
- directory
- filepath
- tagsoup
- text
- lucid
- lucid-htmx >= 0.1.0.4
extra-source-files:
- CHANGELOG.md
- README.md
ghc-options: -Wall
library:
  exposed-modules:
  - Lucid.Generate
  - Lucid.Sanitize
  - Lucid.Combinators
  - Lucid.Supplemental
  source-dirs:
  - src
executables:
  lucid-from-html:
    source-dirs:
    - app
    main: Main.hs
    dependencies:
    - lucid-from-html
tests:
  test:
    main: test.hs
    source-dirs:
      - tests
    dependencies:
      - tasty-golden >= 2.3.1.1
      - bytestring >=0.10
      - tasty >=0.8
      - lucid-from-html
stability: Experimental
